version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:latest
    deploy:
      replicas: 1
  tango:
    container_name: tango
    ports:
      - '3000:3000'
    build:
      context: ./Tango
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Tango/config.py:/opt/TangoService/Tango/config.py
      - ./Tango/volumes:/opt/TangoService/Tango/volumes
    environment:
      - DOCKER_DEPLOYMENT
      - RESTFUL_KEY
      - DOCKER_REDIS_HOSTNAME
      # Path to volumes within the Tango container. Does not need to be modified.
      - DOCKER_VOLUME_PATH
      # Modify the below to be the path to volumes on your host machine
      - DOCKER_TANGO_HOST_VOLUME_PATH
