name: Echo something
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: echo something
        run: |
           echo "hello"
           echo ${{ secrets.TEST }}
